### ISSUE TITLE
Format of text file?

### ISSUE THREAD

**Issue by cygnoir** [bgartenmann/uebersicht-only-this-widget#1]
Hi there. I'm trying to figure out how to format the today.txt file to get this to work. Adding my goal to the first line works, but then I don't know where to add steps 1-3. I've tried a number of different ways, and none of them show up properly (see screenshot).

![screenshot 2015-08-06 22 03 01](https://cloud.githubusercontent.com/assets/1072244/9123369/f35aaea4-3c86-11e5-9cb1-b3bcc80b6f6a.png)

**Comment by iviaxpow3r** [comment]
Hey cygnoir - I just figured this out... the format of the text file is like this:

`goal*step1*step2*step3`

That will make it display correctly. Just replace goal, step1, etc... with what you want it to actually say.

![screen shot 2015-08-25 at 11 49 57 am](https://cloud.githubusercontent.com/assets/12956779/9476064/847ea1c8-4b1f-11e5-97e5-e91f3b54bae5.png)

**Comment by cygnoir** [comment]
Brilliant. Works perfectly. Cheers!
